
GET http://localhost:3000/api/events

###

PUT http://localhost:3000/events


### Get single event:
GET http://localhost:1337/events?slug=throwback-thursdays-with-dj-manny-duke



### Search
GET http://localhost:1337/events?name_contains=manny



### Auth - password
POST http://localhost:1337/auth/local
Content-Type: application/x-www-form-urlencoded

&identifier=sally@gmail.com
&password=Password1


# **Strapi User**
# user: don
# pw: Password1
# email: don@westland.net

# **Website User:**
# user John Doe
# Pw: Password1
# email: john@gmail.com

# user: sally
# Pw: Password1
# email: sally@gmail.com

### Auth - JWT token
GET http://localhost:1337/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjI2MDYxNzA2LCJleHAiOjE2Mjg2NTM3MDZ9.BXtHRkEkGmNZuiobX57ilKKw87rxyUS1_GkMWkHjLXg


### Login
GET http://localhost:3000/api/login


# using events/me path
###
GET http://localhost:1337/events/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjI2NzU2OTcxLCJleHAiOjE2MjkzNDg5NzF9.J7g_25UtztCKuY4s8xgXnXMKk8aHF8aDlxL_iUwG80Y
###
PUT http://localhost:1337/events/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI2NDA1NTgyLCJleHAiOjE2Mjg5OTc1ODJ9.iPMG0EUUxeZCZeVrrV_KLiKOoBkf6eAD5Z5-cWJ60Dc
time: 12:00 AM
